[package]
name = "bbb-servo-controller"
version = "0.1.0"
edition = "2018"

[dependencies]
linux-embedded-hal = "0.4"
pwm-pca9685 = "1.0"
ctrlc = "3.4.4"

actix-web = "4.0"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
