[package]
name = "bbb-servo-controller-wifi"
version = "0.1.0"
edition = "2018"

[dependencies]
linux-embedded-hal = "0.4"
pwm-pca9685 = "1.0"
ctrlc = "3.4.4"

nix = { version = "0.30.1", features = ["term"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" # 시리얼로 받은 설정(JSON)을 파싱하기 위해 추가