[package]
name = "bbb-servo-controller-wifi"
version = "0.1.0"
edition = "2018"

[dependencies]
linux-embedded-hal = "0.4"
pwm-pca9685 = "1.0"
ctrlc = "3.4.4"

rppal = "0.22.1"
serialport = "4.2.2"

nix = { version = "0.30.1", features = ["term"] }